### ISSUE TITLE
Support Rails cops

### ISSUE THREAD

**Issue by dorner** [prontolabs/pronto-rubocop#27]
Rails cops need to be enabled via a command-line option which pronto-rubocop currently doesn't support.

PR forthcoming.

**Comment by aergonaut** [comment]
Does enabling them in your `.rubocop.yml` not work? See: https://rubocop.readthedocs.io/en/latest/cops/#rails

**Comment by fdutey** [comment]
actually, pronto has a very strange way of applying rubocop config.

you don't get the same results by running pronto and rubocop.

**Comment by doomspork** [comment]
Can you expand on that @fdutey? Is it a `rubocop` version difference?
