### ISSUE TITLE
When RUBOCOP_CONFIG is not provided, it does not infer .rubocops.yml

### ISSUE THREAD

**Issue by volkanunsal** [prontolabs/pronto-rubocop#33]
I have a `.rubocops.yml` file in my app's main directory. I run pronto from the same directory. This extension is enabled in the configurations. When pronto runs, it doesn't use `.rubocops.yml` configurations, but instead uses the default configurations of the gem. I think my expectation was that the default value of RUBOCOP_CONFIG would be `.rubocops.yml`. 

Should it be?

**Comment by mknapik** [comment]
The RuboCop uses `.rubocop.yml`, doesn't it? (singular, not plural)

**Comment by doomspork** [comment]
You are correct @mknapik!  I meant to respond yesterday after labeling the issue but I had to jet on short notice.

**Comment by volkanunsal** [comment]
Ohhhhh that explains it. Thanks!
