### ISSUE TITLE
rubocop security vulnerability

### ISSUE THREAD

**Issue by castlese** [prontolabs/pronto-rubocop#34]
There is a low severity security vulnerability in Rubocop versions  < 0.48.1

<img width="293" alt="screen shot 2018-02-07 at 10 11 15" src="https://user-images.githubusercontent.com/1320403/35907918-8f805e98-0bef-11e8-8f2f-25a4ee4634bd.png">

Can pronto-rubocop be updated to use newer version of rubocop?

**Comment by mmozuras** [comment]
@castlese done, released as a minor version: https://github.com/prontolabs/pronto-rubocop/releases/tag/v0.9.1.
