### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by cjonesy** [prontolabs/pronto-rubocop#47]
Are there plans to do a release anytime soon? I'm pretty excited about the github suggestions feature that is in master, but alas it is not available in the latest version of the gem (v0.10.0).

**Comment by scottrobertson** [comment]
👍

**Comment by ashkulz** [comment]
I'm not sure who has the permission to actually release it. @doomspork?

**Comment by skatkov** [comment]
Suggestion feature rocks! Please release ;-)

**Comment by ashkulz** [comment]
Like I said above, I was only recently invited to this org. I think that only @mmozuras (and possibly @doomspork) can do the release to RubyGems.

**Comment by kevin-j-m** [comment]
The work done in 2c16f3f58253e7ac969ec7c46f73f10dd5babbf2 would be great as well so we can update to the latest versions of rubocop. Thanks!

**Comment by hlascelles** [comment]
Hound CI now support the 1.x rubocop family, so a new release would be very welcome. @doomspork or @mmozuras can you oblige? A sign that 2021 may be a better year....

**Comment by ashkulz** [comment]
I've been granted permissions to publish to RubyGems by @doomspork, will try to release by this weekend.

**Comment by hlascelles** [comment]
Hi @ashkulz, could we get a release? Thank you for working on this gem!

**Comment by ashkulz** [comment]
Unfortunately, I wasn't able to get RuboCop 1.0 working -- there were some test failures. Would gladly accept PRs to fix the same, alternatively will try to work on it in a week or so.
