### ISSUE TITLE
Recipe for standard gem?

### ISSUE THREAD

**Issue by jjb** [prontolabs/pronto-rubocop#71]
feature request: Would be cool to have a runner for https://github.com/testdouble/standard - not sure if that would be a subset of this runner or its own runner.

**Comment by shawnwonolo** [comment]
This feature would be really awesome

**Comment by shawnwonolo** [comment]
Oh wait, just saw this https://github.com/julianrubisch/pronto-standardrb lol

**Comment by ashkulz** [comment]
@jjb considering there's already an existing runner, I'm going to close this issue.
