### ISSUE TITLE
Deprecated wrings

### ISSUE THREAD

**Issue by Viktor-Ivliev** [prontolabs/pronto-rubocop#92]
Using the latest version of rubocop (1.65+) we can get these warnings:
```
pronto/rubocop/patch_cop.rb:34: warning: `Cop.all` is deprecated. Use `Registry.all` instead.
pronto/rubocop/patch_cop.rb:62: warning: `inspect_file` is deprecated. Use `investigate` instead.
```

New versions: 
```
Using racc 1.8.1 (was 1.8.0)
Using parallel 1.26.3 (was 1.24.0)
Using parser 3.3.4.2 (was 3.3.1.0)
Using rexml 3.3.6 (was 3.2.8)
Using rubocop-ast 1.32.2 (was 1.31.3)
Using rubocop 1.66.0 (was 1.64.0)
Using rubocop-performance 1.21.1 (was 1.21.0)
```

**Comment by NikoRoberts** [comment]
There is only 2 uses of inspect_file in the codebase and one is already wrapped in a responds_to? conditional that tries investigate if the version of Rubocop supports it [here](https://github.com/prontolabs/pronto-rubocop/blob/bc22f3585ec8506a3473e824a1f8ea91cdd1d424/lib/pronto/rubocop/patch_cop.rb#L71)

The other is in [offense_line.rb](https://github.com/prontolabs/pronto-rubocop/blob/bc22f3585ec8506a3473e824a1f8ea91cdd1d424/lib/pronto/rubocop/offense_line.rb#L81) and does not have this conditional check. So, it should be a pretty straightforward fix?

**Comment by Viktor-Ivliev** [comment]
Hi @NikoRoberts , I think I've found the cause of this behavior.

It really is in the mater branch:
![image](https://github.com/user-attachments/assets/33ccbc6e-ac0a-474a-97d8-e59d88a71e67)

But rubygems published version 0.11.5,

![image](https://github.com/user-attachments/assets/d212d39e-526a-4f4b-be74-3d7a66d62002)

 which contains different code:
 
![image](https://github.com/user-attachments/assets/d5b22446-e651-4161-91f0-ed3ce323ceae)

Consequently, this needs a new version 0.11.6 for rubygems. Or do we need to use the master link directly? (which we don't want to do). 

Thanks for your efforts =)

**Comment by Viktor-Ivliev** [comment]
@ashkulz  Hi, the end of the week is here =)

**Comment by Viktor-Ivliev** [comment]
@ashkulz ping

**Comment by NikoRoberts** [comment]
@Viktor-Ivliev I don't think these reminders serve any positive purpose. This is an open source project, the maintainer is coming back from holiday to their regular life, this is probably pretty far down on their life priorities. 

You have the ability to fork the project and reference that fork in the interim. Please do that instead of potentially risking burning out open source maintainers with daily messages. 🙏

**Comment by Viktor-Ivliev** [comment]
@NikoRoberts I have nothing against it, and wouldn't have pinged if it weren't for the promise of a release by the end of last week. I'm very grateful to the development team, but in turn I'm trying to keep my promises and I want the rest of the world to try to keep theirs too. I promise not to ping here anymore and just wait for the update.

**Comment by Viktor-Ivliev** [comment]
It's not pinging, but what's the status here?

**Comment by Drowze** [comment]
Also looking forward to this!

We use `pronto` coupled with [reviewdog](https://github.com/reviewdog/reviewdog) (for creating PR checks). Unfortunately though, since rubocop spit these warnings at the stderr stream, our stderr is getting pretty big lately and caused us to stumble on [this reviewdog bug](https://github.com/reviewdog/reviewdog/issues/1934). 😅 

Looking forward to a new `pronto-rubocop` release that doesn't raise warnings - that should fix the issue for us 🚀

**Comment by abinoam** [comment]
Thanks @ramil350 for the fix. And thanks @ashkulz for maintaining the gem.

Meanwhile we can use it from master branch like

`gem "pronto-rubocop", git: "prontolabs/pronto-rubocop", require: false`

**Comment by Viktor-Ivliev** [comment]
It's been over a month now, and everyone here is afraid of the burnout of the man who promised a release and disappeared.

**Comment by NikoRoberts** [comment]
> It's been over a month now, and everyone here is afraid of the burnout of the man who promised a release and disappeared. 

Fork it and maintain your own version then?

@ashkulz owes us nothing. This is an open source project that he maintains unpaid, and we should have no problem waiting patiently for a **warning** to be addressed...
@Viktor-Ivliev you likely reduced the motivation @ashkulz did have to do the do the release by expressing your lack of empathy

**Comment by Viktor-Ivliev** [comment]
I was as empathic, as grateful as I could be, until I was cheated. It's just that if I promise someone something, I try to do it. If I don't want to do something, I don't promise anything. It's not about how grateful I am. I'm grateful, it's just about the promise. Especially in master it's all fixed. I'm just interested in the release. Or rather just the fulfillment of the promise. It's just a matter of a few minutes.  Once again, I am grateful to everyone who contributed here, but I don't like to be cheated. If they didn't answer me or wrote - we will release when we have enough functionality, I would keep quiet. But here it was written that they will try to make the release by the end of the week. and it's already been more than a month. Maybe you think I'm toxic, that's your right, I've just been lied to a lot.

**Comment by Viktor-Ivliev** [comment]
@NikoRoberts I'm sorry, I may be angry at the world. Because we were attacked by Russia, which is killing people while being hypocritical in other things. They say they went to defend the Russian-speaking population (who were forced by the Russian government to move there for assemilation), but in the end they are being used as cannon fodder. I am from this population, no one has ever lowered me, but russia took away my house, my life and my parents. But all other countries still blame Ukraine for everything or keep silent as it is profitable for them.... the world is beautiful.

**Comment by abinoam** [comment]
First, I want to express my deepest sympathy for everyone affected by the ongoing war. These are incredibly difficult times, and I can't begin to imagine the challenges many are facing. When people are forced to relocate or live under such unimaginable circumstances, everyday promises and commitments can easily fall by the wayside. Life throws so many obstacles our way—whether it's war, illness, accidents, burnout, or just losing the energy to do things we once considered simple, like a software release.

I can sense that this situation has brought up some strong emotions, and that's totally understandable. In moments like these, it's easy to feel frustration. But I truly believe that patience and understanding are important now more than ever.

In the meantime, I recommend pointing your Gemfile to the latest master branch and using it until the official release is available. Here's how you can do that:

```ruby
gem "pronto-rubocop", git: "prontolabs/pronto-rubocop", require: false
```

I hope this helps and brings some ease to the situation. Please take care of yourself, and know that everyone understands these are extraordinary times.

**Comment by ashkulz** [comment]
[`0.11.6`](https://rubygems.org/gems/pronto-rubocop/versions/0.11.6) has been released to RubyGems. Publishing future versions should be simpler due to implementation of Trusted Publishing workflow (4f2d0f507cc4e45310cb8c509f2a372d0ed141d6) :grin:
