### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by styx** [prontolabs/pronto-rubocop#94]
Here are some new deprecation warnings with latest `Rubocop` (1.67.0):

```
gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:34:
warning: `Cop.all` is deprecated. Use `Registry.all` instead.
```
```
gems/pronto-rubocop-0.11.5/lib/pronto/rubocop/patch_cop.rb:62:
warning: `inspect_file` is deprecated. Use `investigate` instead.
```

**Comment by meleu** [comment]
I noticed that [this commit](https://github.com/prontolabs/pronto-rubocop/commit/82336062b86e5b24fddb22e13c61b11286307e27) (already merged into master) solves the issue.

I think we just need a new release.

**Comment by ashkulz** [comment]
[`0.11.6`](https://rubygems.org/gems/pronto-rubocop/versions/0.11.6) has been released to RubyGems. Publishing future versions should be simpler due to implementation of Trusted Publishing workflow (4f2d0f507cc4e45310cb8c509f2a372d0ed141d6) :grin:
